name: Build
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build
